import Mathlib

open BigOperators
open Set
open Topology

-- Represents the general multilateral externality setting described in the definition.
structure MultilateralExternalitySetting where
  J : Type            -- Type for firms
  I : Type            -- Type for consumers
  [fintypeJ : Fintype J] -- Assumes a finite number of firms for finite summation
  [fintypeI : Fintype I] -- Assumes a finite number of consumers for finite summation

  -- Externality levels generated by each firm j
  h_gen : J → ℝ
  -- Externality levels generated by firms must be non-negative
  h_gen_nonneg : ∀ j, h_gen j ≥ 0

  -- Derived profit function for firm j, taking its own externality level as input
  pi_firm : J → ℝ → ℝ
  -- Profit function is strictly concave (corresponds to π_j''(·) < 0)
  pi_firm_strictly_concave : ∀ j, StrictConcaveOn ℝ (univ : Set ℝ) (pi_firm j)

  -- Derived utility function for consumer i, taking its experienced externality level as input
  phi_consumer : I → ℝ → ℝ
  -- Utility function is strictly concave (corresponds to φ_i''(·) < 0)
  phi_consumer_strictly_concave : ∀ i, StrictConcaveOn ℝ (univ : Set ℝ) (phi_consumer i)

  -- Wealth for consumer i (part of the consumer's total utility φ_i(h_i) + w_i)
  w_consumer : I → ℝ

  -- Context: φ_i'(·) < 0 for all i (negative externality)
  -- This implies the utility function is strictly decreasing.
  phi_consumer_strictly_anti : ∀ i, StrictAnti (phi_consumer i)


-- A depletable (private/rivalrous) externality setting, extending the general setting.
-- This defines how consumer-experienced externalities relate to firm-generated ones in this specific case.
structure DepletableExternalitySetting extends MultilateralExternalitySetting where
  -- Externality experienced by each consumer i. This is determined by the specific externality type.
  h_exp : I → ℝ
  -- The sum of experienced externalities equals the sum of generated externalities
  sum_h_exp_eq_sum_h_gen : ∑ i : I, h_exp i = ∑ j : J, h_gen j

-- A nondepletable (public/nonrivalrous) externality setting, extending the general setting.
-- This defines how consumer-experienced externalities relate to firm-generated ones in this specific case.
structure NonDepletableExternalitySetting extends MultilateralExternalitySetting where
  -- Externality experienced by each consumer i. This is determined by the specific externality type.
  h_exp : I → ℝ
  -- Each consumer experiences the total sum of generated externalities
  h_exp_eq_sum_h_gen : ∀ i : I, h_exp i = ∑ j : J, h_gen j