import Mathlib

open Finset BigOperators
open BigOperators

variable {L : ℕ}

/-- Dot product of price vector and activity vector. -/
noncomputable def profit (p a : Fin L → ℝ) : ℝ :=
  ∑ i : Fin L, p i * a i

/-- A(p): activities generating exactly zero profit at price vector p. -/
def zeroProfitActivities (p : Fin L → ℝ) (activities : Set (Fin L → ℝ)) :
    Set (Fin L → ℝ) :=
  {a ∈ activities | profit p a = 0}

/-- y(p): the profit-maximizing supply set, the convex cone generated by A(p).
    Each element is a nonneg linear combination of zero-profit activities. -/
noncomputable def profitMaxSupplySet (p : Fin L → ℝ) (activities : Set (Fin L → ℝ)) :
    Set (Fin L → ℝ) :=
  {y : Fin L → ℝ |
    ∃ (S : Finset (Fin L → ℝ)) (α : (Fin L → ℝ) → ℝ),
      (↑S : Set (Fin L → ℝ)) ⊆ zeroProfitActivities p activities ∧
      (∀ a ∈ S, 0 ≤ α a) ∧
      y = ∑ a ∈ S, α a • a}