import Mathlib
open Topology

variable {n : ℕ}

/-- The ray generated by a vector `y` in a production set `Y` is the set of all positive scalar
    multiples of `y` that lie in `Y`. -/
def ray (Y : Set (Fin n → ℝ)) (y : Fin n → ℝ) : Set (Fin n → ℝ) :=
  {ybar ∈ Y | ∃ α : ℝ, α > 0 ∧ ybar = α • y}