import Mathlib
open BigOperators Finset

variable {L M : ℕ}

/-- The linear activity production set generated by M elementary activities in ℝ^L.
    Y = {y ∈ ℝ^L : y = Σ_{m=1}^M α_m · a_m for some (α_1,…,α_M) ≥ 0}.
    This is the conic (nonnegative) hull of the activity vectors, forming a polyhedral cone. -/
noncomputable def LinearActivityProductionSet
    (a : Fin M → (Fin L → ℝ)) : Set (Fin L → ℝ) :=
  {y | ∃ α : Fin M → ℝ, (∀ m, 0 ≤ α m) ∧ y = ∑ m : Fin M, α m • a m}