import Mathlib

/-- A one-consumer stationary planning problem (MWG 20.F.1) with policy function
    and modified golden rule steady state. -/
structure StationaryPlanningProblem where
  /-- Per-period utility depending on current and next capital -/
  u : ℝ → ℝ → ℝ
  /-- Discount factor δ ∈ (0, 1) -/
  δ : ℝ
  hδ_pos : 0 < δ
  hδ_lt_one : δ < 1
  /-- Policy function ψ mapping current capital to optimal next-period capital -/
  ψ : ℝ → ℝ
  /-- Policy function yields nonnegative capital -/
  hψ_nonneg : ∀ k, 0 ≤ k → 0 ≤ ψ k

/-- The equilibrium trajectory generated by iterating the policy function
    starting from initial capital k₀: (k₀, ψ(k₀), ψ(ψ(k₀)), ...) -/
noncomputable def StationaryPlanningProblem.trajectory (P : StationaryPlanningProblem) (k₀ : ℝ) : ℕ → ℝ :=
  fun t => P.ψ^[t] k₀

/-- A modified golden rule steady state for discount factor δ is a fixed point k = ψ(k). -/
def StationaryPlanningProblem.IsModifiedGoldenRule (P : StationaryPlanningProblem) (k : ℝ) : Prop :=
  P.ψ k = k