import Mathlib

/-- If A is not spannable by the given asset structure, there are two serious difficulties:
(1) The value of a production plan cannot be computed from current asset prices by arbitrage
    (the price quoting problem).
(2) Because of unlimited short sales, even a small new asset not generated by the current
    asset structure increases the span by one whole extra dimension, potentially having
    dramatic effects on prices (the price taking problem).
There is then no reason for owners' preferences to be dictated merely by wealth increase
at pre-introduction prices. -/
axiom incomplete_market_difficulties
    (S K : ℕ) (R : Matrix (Fin K) (Fin S) ℝ) (hR : R.rank < S) :
    (∃ v : Fin S → ℝ, v ∉ Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R)) ∧
    (∀ v : Fin S → ℝ, v ∉ Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R) →
      Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R) <
      Submodule.span ℝ (insert v (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R)))

theorem Claim_19G_b
    {S K : ℕ} (R : Matrix (Fin K) (Fin S) ℝ)
    (hR : R.rank < S) :
    (∃ v : Fin S → ℝ, v ∉ Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R)) ∧
    (∀ v : Fin S → ℝ, v ∉ Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R) →
      Submodule.span ℝ (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R) <
      Submodule.span ℝ (insert v (Set.range fun z : Fin K → ℝ => Matrix.vecMul z R))) :=
  incomplete_market_difficulties S K R hR