import Mathlib

/-- A preference relation on ℝ² has L-shaped indifference curves (perfect complements) -/
axiom LShapedIndifferenceCurves (pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop) : Prop

/-- The Slutsky substitution matrix is zero (implied by L-shaped indifference curves) -/
axiom SlutskySmatrixZero (x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ)) : Prop

/-- The demand function satisfies the ULD (Uncompensated Law of Demand) property:
    (p' - p) · (x(p', w) - x(p, w)) ≤ 0 for all p, p', w -/
axiom ULDProperty (x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ)) : Prop

/-- A preference relation is homothetic: x ≿ y ↔ αx ≿ αy for all α > 0 -/
axiom Homothetic (pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop) : Prop

/-- Demand function is generated by the preference relation -/
axiom GeneratedBy (x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ))
  (pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop) : Prop

/-- L-shaped indifference curves imply the Slutsky matrix is zero -/
axiom lshaped_implies_slutsky_zero
  {pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop}
  {x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ)}
  (hgen : GeneratedBy x pref)
  (hlsh : LShapedIndifferenceCurves pref) :
  SlutskySmatrixZero x

/-- With S = 0 and ULD, the wealth effect must be proportional to demand,
    which forces homotheticity -/
axiom slutsky_zero_uld_implies_homothetic
  {pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop}
  {x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ)}
  (hgen : GeneratedBy x pref)
  (hzero : SlutskySmatrixZero x)
  (huld : ULDProperty x) :
  Homothetic pref

/-- MWG Exercise 4.C.4: If preferences have L-shaped indifference curves
    (perfect complements) and demand satisfies ULD, then preferences are homothetic. -/
theorem Claim_4C_u
  (pref : (Fin 2 → ℝ) → (Fin 2 → ℝ) → Prop)
  (x : (Fin 2 → ℝ) → ℝ → (Fin 2 → ℝ))
  (hgen : GeneratedBy x pref)
  (hlsh : LShapedIndifferenceCurves pref)
  (huld : ULDProperty x) :
  Homothetic pref := by
  have hzero : SlutskySmatrixZero x := lshaped_implies_slutsky_zero hgen hlsh
  exact slutsky_zero_uld_implies_homothetic hgen hzero huld