import Mathlib

open Finset BigOperators
open BigOperators

/-- A positive representative consumer for an aggregate demand function `x`.
    It consists of a rational preference relation `pref` on ℝ^L₊ such that
    for every price-wealth pair (p, w), the aggregate demand x(p, w) is the
    Walrasian demand generated by `pref`: any affordable bundle y ≠ x(p, w)
    is weakly dispreferred. -/
structure PositiveRepresentativeConsumer (L : ℕ)
    (x : (Fin L → ℝ) → ℝ → (Fin L → ℝ)) where
  /-- The preference relation ≿ on ℝ^L₊ -/
  pref : (Fin L → ℝ) → (Fin L → ℝ) → Prop
  /-- ≿ is reflexive -/
  pref_refl : ∀ a, pref a a
  /-- ≿ is transitive -/
  pref_trans : ∀ a b c, pref a b → pref b c → pref a c
  /-- ≿ is total (complete) -/
  pref_total : ∀ a b, pref a b ∨ pref b a
  /-- x(p,w) is the Walrasian demand: any affordable bundle y ≠ x(p,w) satisfies x(p,w) ≿ y -/
  walrasian_demand : ∀ (p : Fin L → ℝ) (w : ℝ) (y : Fin L → ℝ),
    (∀ i, 0 ≤ y i) →
    ∑ i, p i * y i ≤ w →
    y ≠ x p w →
    pref (x p w) y