import Mathlib

open Fintype

/-- The total number of distinct sequences of outcomes for N independent chance events,
    each with K possibilities, is equal to K to the power of N. This shows that
    the set of all possible outcomes for multiple chance moves can be equivalently
    generated by a single chance move selecting from the full set of sequences. -/
theorem Claim_7_3_a_outcome_cardinality_equivalence (k N : ℕ) :
    Fintype.card (Fin N → Fin k) = (Fintype.card (Fin k)) ^ N :=
by
  simp [Fintype.card_fin, Fintype.card_fin]