import Mathlib

open Set Function
open Topology

noncomputable section

-- A cost function satisfies properties 1-7 of Theorem 3.2
-- (nonnegative, nondecreasing in q, homogeneous of degree 1 in w,
--  concave in w, continuous, etc.)
axiom CostFnProperties (c : (Fin n → ℝ) → ℝ → ℝ) : Prop

-- A production function maps inputs to output
axiom ProductionFn : ℕ → Type
axiom generates_cost (n : ℕ) (f : ProductionFn n) (c : (Fin n → ℝ) → ℝ → ℝ) : Prop

-- Duality theorem: any valid cost function is generated by some production function
axiom cost_function_duality (n : ℕ) (c : (Fin n → ℝ) → ℝ → ℝ) :
  CostFnProperties c → ∃ f : ProductionFn n, generates_cost n f c

variable {n : ℕ}

/-- Any function with all the properties of a cost function (properties 1-7 of Theorem 3.2)
    generates some production function for which it is the cost function.
    This is the cost-function side of the production-cost duality. -/
theorem Claim_3_4_b (c : (Fin n → ℝ) → ℝ → ℝ) (hc : CostFnProperties c) :
    ∃ f : ProductionFn n, generates_cost n f c :=
  cost_function_duality n c hc

end