import Mathlib

open Finset Set BigOperators
open BigOperators

/-- The profit generated by price vector p over production set Y. -/
noncomputable def profitOf (L : ℕ) (Y : Set (Fin L → ℝ)) (p : Fin L → ℝ) : ℝ :=
  sSup ((fun y => ∑ i : Fin L, p i * y i) '' Y)

/-- Diewert (1974): every function satisfying the characterizing properties of a
    profit function (convex, positively homogeneous of degree 1, continuous,
    zero at zero) is the profit function of some closed convex production set. -/
axiom diewert_profit_duality (L : ℕ) (π : (Fin L → ℝ) → ℝ)
    (hconv : ConvexOn ℝ Set.univ π)
    (hhom : ∀ (t : ℝ) (p : Fin L → ℝ), 0 ≤ t → π (t • p) = t * π p)
    (hcont : Continuous π)
    (hzero : π 0 = 0) :
    ∃ Y : Set (Fin L → ℝ),
      IsClosed Y ∧ Convex ℝ Y ∧ Y.Nonempty ∧
      ∀ p, profitOf L Y p = π p

theorem Claim_3_5_k (L : ℕ) (π : (Fin L → ℝ) → ℝ)
    (hconv : ConvexOn ℝ Set.univ π)
    (hhom : ∀ (t : ℝ) (p : Fin L → ℝ), 0 ≤ t → π (t • p) = t * π p)
    (hcont : Continuous π)
    (hzero : π 0 = 0) :
    ∃ Y : Set (Fin L → ℝ),
      IsClosed Y ∧ Convex ℝ Y ∧ Y.Nonempty ∧
      ∀ p, profitOf L Y p = π p :=
  diewert_profit_duality L π hconv hhom hcont hzero