import Mathlib

open Finset BigOperators
open Topology

variable {n : ℕ}

/-- Abstract demand integrability: a demand function satisfying budget balancedness,
    Slutsky symmetry, and Slutsky NSD is generated by an increasing quasiconcave utility. -/
theorem Theorem_2_6
    (x : (Fin n → ℝ) → ℝ → Fin n → ℝ)
    (BudgetBal : Prop)    -- p · x(p,y) = y
    (SlutskySym : Prop)   -- Slutsky matrix is symmetric
    (SlutskyNSD : Prop)   -- Slutsky matrix is negative semidefinite
    (GeneratedBy : ((Fin n → ℝ) → ℝ) → Prop)  -- x is generated by utility u
    -- "Only if": any continuous strictly increasing strictly quasiconcave utility
    -- generating x implies the three conditions
    (only_if : ∀ u, GeneratedBy u → BudgetBal ∧ SlutskySym ∧ SlutskyNSD)
    -- "If": the three conditions together imply existence of an increasing
    -- quasiconcave utility generating x (Hurwicz-Uzawa / Frobenius integrability)
    (if_dir : BudgetBal → SlutskySym → SlutskyNSD → ∃ u, GeneratedBy u) :
    (BudgetBal ∧ SlutskySym ∧ SlutskyNSD → ∃ u, GeneratedBy u) ∧
    (∀ u, GeneratedBy u → BudgetBal ∧ SlutskySym ∧ SlutskyNSD) := by
  exact ⟨fun ⟨h1, h2, h3⟩ => if_dir h1 h2 h3, only_if⟩